### ISSUE TITLE
[ChatChart] Design

### ISSUE THREAD

**Issue by Lionirdeadman** [aikaterna/aikaterna-cogs#10]
I think it should look more in touch with your other image cogs so these should be changed :  
-Font (Should be bold and probably bigger)
-Transparency (Transparent instead of white)
-More compact (There is some unnecessary space above and below)

Thanks!

**Comment by aikaterna** [comment]
Hello, while these suggestions were not explicitly followed, there has been a general improvement to chatchart done in #14 and a subsequent commit. This new formatting will be added to the v3 version as well. Thank you for the suggestions.
