### ISSUE TITLE
[Warcraftlogs] Have 'wclgear' pull gear from latest raid

### ISSUE THREAD

**Issue by tsposato** [aikaterna/aikaterna-cogs#107]
At the moment wclgear produces output from a raid over a week ago when there are a number of raids that have been logged since.

Is there a way to use the latest raid for this information?

**Comment by aikaterna** [comment]
One thing that could be happening is that sometimes gear is not recorded on WCL and in that case the cog tries to fall back to a previous log that actually has gear listed. If you do have gear listed on your later logs, could you please provide me with log links to test so I can take a look at this? If you wish to keep your log links less publicly visible, please feel free to DM me on Discord if we share servers, or friend request aikaterna#1393.

**Comment by aikaterna** [comment]
Hey there, thanks for the chat in Discord. https://github.com/aikaterna/aikaterna-cogs/commit/fa4c8481b8331dd2b7f5911c20646d7843b08948 should theoretically resolve this for you.

**Comment by aikaterna** [comment]
Still working on this.

**Comment by aikaterna** [comment]
Can you try updating and let me know how it goes? Should actually be resolved this time in 1461706.

**Comment by aikaterna** [comment]
I added another small commit after that so please make sure you're all the way up to date. I'm going to close this again but please don't hesitate to make another issue if there are other problems with encounter sorting or anything else.
