### ISSUE TITLE
[Hunting] Feature request

### ISSUE THREAD

**Issue by aikaterna** [aikaterna/aikaterna-cogs#109]
Since there is a to-do for hunting, I will post my feature request here :-) 

I would like to see a economy integration with hunting. I have thinking about it, maybe selling the animals or even process them to make them more worth to gain some money. To make you lose some money, you need to buy a gun to shoot and ammunition. 
Or maybe even go deeper with it and make guns decay and you need to buy a new one, etc etc.

_Originally posted by @Brandjuh in https://github.com/aikaterna/aikaterna-cogs/issues/102#issuecomment-617992169_

**Comment by lakai** [comment]
Could you add reaction time to the "bang" shown?  Too many people are using bots and it ruins the game for everyone.  Ty

**Comment by aikaterna** [comment]
@lakai what is your idea of "reaction time to the bang" ?

**Comment by lakai** [comment]
Have the bot say "@user has killed a Penguin (0.21ms)"  Something like that.  I understand there will be latency but at least there will be proof as to who is using a bot ( even though its clear who is).

**Comment by aikaterna** [comment]
Thanks for the info, I will add that in a later commit.

**Comment by aikaterna** [comment]
@lakai you can find your request in fbf67d6.

**Comment by aikaterna** [comment]
I am closing this issue in an attempt to keep the issues here a bit cleaner. The bang time request should have been on a new issue.
