### ISSUE TITLE
[RSS] Feature Request - Role mentions to notify about new rss feed

### ISSUE THREAD

**Issue by owocado** [aikaterna/aikaterna-cogs#155]
Hi aika,

Just putting this in here instead of posting in your server or support channel because it would get lost there. 
This feature request is for RSS cog to notify and mention a role when a new rss feed comes out, just like how Sinbad's cog had/has.
The reason for this request is, personally speaking, in my community server, we have over 80+ webtoon readers plus manga readers too. So when a new webtoon or manga chapter comes out, bot would post the feed + ping the role which was linked with the said rss feed. That way, it relieves my mods to manually ping the role and it automates the process.

I am sure this feature request will be useful to a lot of people for similar use case in their community who will be using this RSS cog. 

I know I could already achieve this with current cog setup by using non embed option for rss feed and putting role mention string in the said rss template but hey embeds looks cool. :awesome:
And putting role mention inside embeds doesn't work for my use case here. :pikaLul:
And by using embed option I can also utilize showing content images so my users can get a kind of glimpse/preview of the newly released chapter. That's why I am particularly relying on embed option for RSS feeds. 

I think you have probably planned for this feature or thought about implementing it at some point in the future.

I was planning to take the same logic from Sinbad's rss cog and make a PR to this one here, but I was unsure if you would wanna do it that way. I am assuming you probably wanna implement it in your own way with a different logic in mind but I'm unsure on this one, it's just my gut feeling. Please let me know what are your thoughts on this feature request.

**Comment by aikaterna** [comment]
After talking with Jack he may look into adding a role ping option to his RSSNotifier cog as you can see by the linked issue.
