### ISSUE TITLE
[Hunting] Hunting sometimes hang/doesn't return

### ISSUE THREAD

**Issue by deXxterlab97** [aikaterna/aikaterna-cogs#162]
It happened twice. Sometimes a new animal to hunt would appear way later than it was set.

Occurrence 1 : 
Last pet to appear was on 8/28/2020, was a duck that quacks
User shot it in 5.515s

- Then a user reminded me that we haven't a bird in weeks, on Sep 22. 
- I loaded it because I thought it got unloaded (load hunting) but bot said it's already loaded
- then I started it (hunting start) and bot said we're already hunting.

then the admin typed `hunting next` and it shows 

> The next occurrence will be in 614 hours and 39 minutes.

I thought it had something to do with wrong timing, so I set it (copy pasted from when I initially added it) again
`[p]hunting timing 3600 4200 20  `

but didn't work so I reloaded it and it works fine

The last time I set timing was on 8/21 of that year at 1:44 AM 
`~hunting timing 120 240 20`
Then I felt the time too short so I did this at 2:25 AM at the same day
`~hunting timing 3600 7200 20`
and fine tuned it at 2:28 AM
`~hunting timing 3600 4200 20`

Did not touch hunting setting related commands ever since, except I did add some alias to hunting leaderboard and score.

Occurrence 2 : 
This time user are more aware and reported me earlier
The last bird to appear was on 10/01
Then I suppose it went quiet 

Checked hunting next on the 3rd of October 10/03 

`The next occurrence will be in 36 hours and 43 minutes.`
 
Now I just reloaded adventure and it works. No other command was run (except Hunting next).

Hunting adventure version is 3.1.3 when the 2nd time it was broken. 

More info, `[p]hunting next` was tied to admin role (addadminrole).

**Comment by aikaterna** [comment]
Hunting is on Vertyco's repo now at https://github.com/vertyco/vrt-cogs. If you still have issues with this please let him know with an updated issue.
