### ISSUE TITLE
[RSS] Max Character Limit For Feeds

### ISSUE THREAD

**Issue by TwinDragon** [aikaterna/aikaterna-cogs#177]
I've had this thought in my head for a bit, but as I mentioned in the Discord channel, this might actually prove useful for some people who don't want to have, say multiple embeds for feeds that get pretty long.

For example, one feed I follow sometimes posts some pretty long blog entries, especially when it's detailing certain new features for a game. If I could limit the max characters to, say around 500-700 characters, it would cut back on the spamminess of the feed, and still look elegant.

I think the default should be to post the entire feed, and then an optional parameter to put in a max character limit.

`rss add <feed> [channel] <url> [max_limit]`

For existing feeds, maybe something like this:
`rss maxlimit <feed> [channel]`

Couple ideas anyway.

**Comment by aikaterna** [comment]
9cee901
