### ISSUE TITLE
[Feature/Advice Request] Ability to use !seen across a Discord-IRC bridge

### ISSUE THREAD

**Issue by Kovaelin** [aikaterna/aikaterna-cogs#19]
This is likely outside the normal scope of Red cogs, but I'm wondering, are you familiar with the [Discord-IRC project](https://github.com/reactiflux/discord-irc)?

Do you think it would be possible to use !seen from the Discord side and see if a user is online in IRC? Do you think it's something you could do or know where to start? Thank you.

Related links:
https://github.com/reactiflux/discord-irc/issues/287
https://github.com/reactiflux/discord-irc/issues/347

**Comment by aikaterna** [comment]
Sorry, out of the scope of these cogs and the project you linked is not written in Python.
