### ISSUE TITLE
[Chatchart] Caching old results

### ISSUE THREAD

**Issue by HelmicNewciv** [aikaterna/aikaterna-cogs#193]
Since you can specify the number of posts chatchart will look up, users tend to find it extremely amusing to put massive numbers in and making the bot be busy for multiple days in a row.  And then of course other users get annoyed with "Leninbot is typing..." being permanently under the chat.

While having an option to limit the number of posts it'll search would be nice, it'd also be handy if the command could cache old results, so once it hits a date prior to the newest post in the cache it can safely assume that there at least have been no new posts.retroactively added, making it so posting .chatchart 999999999999 for the 80th time that day far less annoying.  It'll still count posts that have since been deleted, but who gives a fuck.

**Comment by aikaterna** [comment]
If you're up to date on the cog, you can set a bot-wide message limit on the command. I'm not interested in adding anything regarding caching as I will have to disclose that to users regarding privacy and the bot storing information about their messages. Alternatively you can also manage users' access to the command with the core permissions cog.
