### ISSUE TITLE
[Hunting] Wipe settings suggestion / request

### ISSUE THREAD

**Issue by xBlackAttack** [aikaterna/aikaterna-cogs#194]
for hunting an easy way can come an option such as wipe the leaderboard
server and global wipe

**Comment by aikaterna** [comment]
If I implement this, it will only be a global wipe. The only thing the server leaderboard does is only show people in your server. So if there was a server wipe, it would wipe those people's scores globally... which is not a good idea.

**Comment by xBlackAttack** [comment]
if it doesn't, it can be a global wipe yeah
