### ISSUE TITLE
[Dungeon] Offer Kick as an Alternitive to Ban

### ISSUE THREAD

**Issue by Ryonez** [aikaterna/aikaterna-cogs#201]
We've been dealing with a user determined to create as many alts as needed to annoy a server.
I came across the dungeon cog as an alternative to writing up my own "age gate" cog, and looks like a good tool to use. Now, I'd love to let it preform auto actions, however we will get users who legitimately have new accounts. These people we do not wish to ban.

I'd like to propose that we have the ability to pick between banning or kicking for action the dungeon cog can take automatically. This will allow users to return in X days without them having to find a way to reach out to staff and have us remove them from the banlist.

**Comment by aikaterna** [comment]
I might consider a kick/ban toggle for blanket behaviour but that's about it, no special conditions per user. I'm keeping this open until I write this or decide not to.

**Comment by aikaterna** [comment]
Hi, I've decided to remove support for this cog. I would suggest that you migrate to/use Twentysix's Defender cog instead. The dungeon cog won't be removed from my repo until I finish the dpy 2.0 changes so you still have a little time if you want to fork it or do it yourself.

**Comment by Ryonez** [comment]
I use the Defender cog as well, however this cog has features that Defender doesn't have currently.

Thank you for letting me know, I'll look at bringing this into my own repo to maintain in a bit.
