### ISSUE TITLE
[Dungeon] Cofigure Autoban Triggers

### ISSUE THREAD

**Issue by Ryonez** [aikaterna/aikaterna-cogs#202]
I'd like to request a bit of flexibility to the autoban system.
So, I might wish to ban/kick users who have a new account, but not necessarily for having a default pfp. But, I do want the default pfp to cause them to get the Dungeon Role.

**Comment by aikaterna** [comment]
I'm not interested in writing this.

**Comment by Ryonez** [comment]
Would you be against a fork being of this cog being made then?
