### ISSUE TITLE
RSS not recognize link 

### ISSUE THREAD

**Issue by henriquemod** [aikaterna/aikaterna-cogs#203]
Cog is having problems with some rss feed that i dont know why

For examble this link isnt recognized https://valorantzone.gg/feed/

While this do https://www.hltv.org/rss/news

They look similar but somehow the cog says "Invalid or unavailable URL."

**Comment by Drapersniper** [comment]
The first link you send is not a true valid RSS.
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fvalorantzone.gg%2Ffeed%2F (Here's the explanation)

I would suggest contacting the maintainers and informing them.

**Comment by aikaterna** [comment]
I'm closing this issue as it is not the cog that has an issue. The feedparser library that the cog uses can't read this feed for the reasons Draper mentioned above. I'm intending to add slightly more descriptive error messages in the future but even so it wouldn't have fixed the feed.
