### ISSUE TITLE
[Dungeon] Auto-ban Triggers Even When Disabled

### ISSUE THREAD

**Issue by Ryonez** [aikaterna/aikaterna-cogs#204]
As the title stats, the cog is auto-banning users despite that feature being disabled.

Settings:
![image](https://user-images.githubusercontent.com/16157130/106713852-e7b11300-665f-11eb-929f-69b8f7b0d381.png)

Result:
![image](https://user-images.githubusercontent.com/16157130/106713894-f4356b80-665f-11eb-82a3-17099ad14dc5.png)

**Comment by Drapersniper** [comment]
Banished is not the same as banned; in this case the users are being given the Dungeon role. "Unverified" if a user is banned the message you shown isnt displayed.

**Comment by Ryonez** [comment]
Ah, you're right.

Sorry, we had some trouble with the cog banning them before with required toggling the setting a few times for it to come right. I guess I was really tired and forgot to properly check the audit logs. Sorry for the waste of time.
