### ISSUE TITLE
[Region] [Feature Request] Command to reconnect to same region

### ISSUE THREAD

**Issue by Technetium1** [aikaterna/aikaterna-cogs#214]
A command to reconnect to the same region when there are issues with server load. Seems someone has done most (all?) of the work https://github.com/fixator10/Fixator10-Cogs/blob/8c0de83050b04485d658e438d73acba2b3c8e143/adminutils/adminutils.py#L92-L113

**Comment by aikaterna** [comment]
I take it this request is for the region cog I have. I don't have an interest in saving old regions, it is a simple cog to switch the guild voice region and that is all.
