### ISSUE TITLE
ChatChart "isn't available from that repo"

### ISSUE THREAD

**Issue by RecklessJames** [aikaterna/aikaterna-cogs#22]
Constantly saying this, despite me being 101% sure I'm typing it right. Maybe you should LOOK INTO IT!

**Comment by aikaterna** [comment]
It works fine. Please visit the Red support server or the Red cog server if you need help with adding it, and please have a screenshot ready of you adding the repo to your bot, and information about whether your bot is v2 or v3. Also, don't be rude.
