### ISSUE TITLE
Dadjoke Output Formatting issue

### ISSUE THREAD

**Issue by Vault108** [aikaterna/aikaterna-cogs#233]
Sometimes the output will use `â€™` instead of `'` 
Not sure what is happening as it works fine one moment, and it's not the next. 
I have attached an example: 
![S0capkq](https://user-images.githubusercontent.com/44564111/119210656-731dab00-ba7b-11eb-9133-33f79bde6e75.png)
Bot / System Details: 

- Python 3.8.5
- Discord.py 1.7.1
- Bot 3.4.9
I am not home at the moment once home I can provide more details / further testing

**Comment by aikaterna** [comment]
Fixed by merged PR.
