### ISSUE TITLE
[Warcraftogs]

### ISSUE THREAD

**Issue by scarecr0w12** [aikaterna/aikaterna-cogs#235]
I've begun getting the error of:
WCL API Error: Unauthenticated.

My API keys have not changed, I've even tried new fresh ones and still erroring. This started occurring after Warcraftlogs went down for a while today for maintenance. Was there a change in their API system?

**Comment by aikaterna** [comment]
Not that I know of, and it works for me. I'm probably also depreciating the cog because I don't play Burning Crusade Classic.
