### ISSUE TITLE
Red Update

### ISSUE THREAD

**Issue by xNightWulf** [aikaterna/aikaterna-cogs#24]
rndstatus, partycrash, pingtime, chatchart, nolinks and tools no longer work on the updated version of red giving the error: 

RuntimeError: The Tools cog in the tools.tools package does not inherit from the commands.Cog base class. The cog author must update the cog to adhere to this requirement.

and so on.

**Comment by aikaterna** [comment]
Fixed with https://github.com/aikaterna/aikaterna-cogs/commit/d8cd36f8ff419821c3eb8714d9ac8473e73e5b0f
