### ISSUE TITLE
[Update Request] (discordexperiments) New discord activities 

### ISSUE THREAD

**Issue by ghost** [aikaterna/aikaterna-cogs#248]
Please add the new discord activities, if possible! They also updated the YouTube activity to include a remote control that can be toggled by the owner, the bot still launches the first version. Thanks Aika!
![September29-143402-VibrantKakapozmu2G9c3](https://user-images.githubusercontent.com/75867173/135336536-4ad073c8-6b74-4a03-b198-fb47e73521df.png)

**Comment by aikaterna** [comment]
I need the activity IDs, which I don't have. Do you?

**Comment by ghost** [comment]
Are they essentially application client IDs?

**Comment by aikaterna** [comment]
They are the IDs you can see in the cog code, a standard snowflake ID.

**Comment by aikaterna** [comment]
Seems like I may have just run across a few of them for the new things. We'll see what happens when I have time to look at this.

**Comment by ghost** [comment]
Letter Tile: 879863686565621790
Word Snacks: 879863976006127627
Doodle Crew: 878067389634314250
Updated Youtube Watch Together: 880218394199220334

If you visit ID.discordsays.com it partially loads the games so I think these should work!

**Comment by aikaterna** [comment]
Thanks for that.

**Comment by aikaterna** [comment]
https://github.com/aikaterna/aikaterna-cogs/commit/82505acbf5a137275390fef8b15abc443290441a
