### ISSUE TITLE
[Dictionary] Synonym/Antonyms with the words true/false in them are replaced improperly

### ISSUE THREAD

**Issue by Aioxas** [aikaterna/aikaterna-cogs#249]
Example: searching for "word" returns "falsehood"as a word, but this gets caught in the replace function, so it becomes ""False"hood", thus making this an invalid json.

Solution: Specify that you want to convert ": true" and ": false" into ': "True"' and ': "False"' respectively

**Comment by aikaterna** [comment]
Thanks man.
https://github.com/aikaterna/aikaterna-cogs/commit/6ae25b4dbb63a0f91b89158063fe45059d3bf6ac
