### ISSUE TITLE
[RSS] Git commits with the same title but different links don't show up

### ISSUE THREAD

**Issue by Aithne99** [aikaterna/aikaterna-cogs#254]
How to reproduce: commit two completely different things to a repo using the same title (such as "update readme") about ten minutes apart, with nothing inbetween. Since the time validation requires that either BOTH the links and the title are the same or NEITHER are in the case that time tags for both entries exist, the second commit will not be posted by the bot.

**Comment by aikaterna** [comment]
Hi, https://github.com/aikaterna/aikaterna-cogs/commit/1792e683f3da175fee2d9e18205847864bbc45af should fix this. Thanks for the report.
