### ISSUE TITLE
[discordexperiments] New game release

### ISSUE THREAD

**Issue by ghost** [aikaterna/aikaterna-cogs#257]
New game added to the Discord Games Lab Server:

Checkers In The Park: 832013003968348200
![November12-195902-CarefulIraniangroundjayJsdUCCGu](https://user-images.githubusercontent.com/75867173/141601659-fd64d380-d5f0-4568-ae8f-658bb405ab4b.png)

**Comment by aikaterna** [comment]
https://github.com/aikaterna/aikaterna-cogs/commit/9e81723b8b7863c8bf05c23fdb6b85855bc4998d
