### ISSUE TITLE
[RSS] Consider changing how feeds for unavailable channels are handled

### ISSUE THREAD

**Issue by Jackenmen** [aikaterna/aikaterna-cogs#260]
Right now, the RSS feeds for the channels that the bot no longer has access to are cleared. This means that a temporary kick of the bot (or bot getting its permissions in a channel temporarily revoked) results in all the feed configuration being lost. This is, in my opinion, unexpected behavior from the user's perspective.
For servers/channels with a lot of feeds set up, this might not be that simple to recover, and adding all feeds again along with any custom configuration (templates) can take some time and is a bit of an annoyance.

Please consider changing this behavior to instead simply ignore these channels or do something else that doesn't result in a complete loss of feed configuration.

**Comment by aikaterna** [comment]
https://github.com/aikaterna/aikaterna-cogs/commit/474619a858e9ff5b65e4000e502a40ae55a7e1a1
