### ISSUE TITLE
[Reminder] __init__ is async def, function itself is not

### ISSUE THREAD

**Issue by FixedThink** [aikaterna/aikaterna-cogs#299]
https://github.com/aikaterna/aikaterna-cogs/blob/5de753e2bfa69703e56e1ce5354e4c8bbf08b86d/reminder/__init__.py#L11-L12

In the Reminder cog, the `__init__` file _seems_ async, but the function body itself is fully sync. I don't know if the function call was meant to be just `def` (i.e. the 3.4 way) or whether the `bot.add_cog()` call is meant to be awaited (the 3.5 way), so hence why I am just opening an issue.

**Comment by aikaterna** [comment]
People have been able to use async setups in cogs since early 2018 in Red V3. You're right that there's no point to it here because there's nothing to await, but it's not hurting anything either. FWIW my cogs also target the latest supported version of Red, which is currently 3.4.x and not 3.5.
