### ISSUE TITLE
[Tools] whatis returning a type error on the dpy2 branch.

### ISSUE THREAD

**Issue by japandotorg** [aikaterna/aikaterna-cogs#304]
```py
Traceback (most recent call last):
  File "/root/MELON/lib/python3.11/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/Red-DiscordBot/data/MELON/cogs/CogManager/cogs/tools/tools.py", line 815, in whatis
    self.bot.guilds
TypeError: unsupported operand type(s) for +: 'SequenceProxy' and 'SequenceProxy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/MELON/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "/root/MELON/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/MELON/lib/python3.11/site-packages/discord/ext/commands/core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: unsupported operand type(s) for +: 'SequenceProxy' and 'SequenceProxy'
```

**Comment by aikaterna** [comment]
What did you use the command on?

**Comment by japandotorg** [comment]
> What did you use the command on?

I found the error laying around in my errorlogs, this is the exact command with the id to be specific `..whatis 1099281087835942922`, my bot is currently timedout for hitting 429 too many requests, so I cannot really check it any soon, but if i do i'll send an update here!

**Comment by aikaterna** [comment]
Appreciate it, would be good to know what the target is but I might be able to work with that if you're having trouble.

**Comment by japandotorg** [comment]
tried a lot of things but failed to get much info about the ID, but this is new ![](https://cdn.melonbot.io/328.png)

**Comment by aikaterna** [comment]
Hi there, this should be fixed in https://github.com/aikaterna/aikaterna-cogs/commit/fac5d84a7e76509a9700f61a3e7dae306c6121ee. Note there are a few open issues with Tools currently regarding sticker id use in whatis and forum channels not having an implementation yet.
