### ISSUE TITLE
bozo-feed-parse-error

### ISSUE THREAD

**Issue by BigLOnline** [aikaterna/aikaterna-cogs#319]
Bozo feed: feedparser is unable to parse the response from *site with rss*, ive had this issue with a few installs. seems its a hit or miss. unsure whether im even able to provide logs or if this is normal

**Comment by aikaterna** [comment]
Please provide the received content preview for one of those feeds.

**Comment by BigLOnline** [comment]
![image](https://github.com/aikaterna/aikaterna-cogs/assets/70815584/09f2cb6d-4073-43b8-a170-d1434b2b2373)
ive had this same rss feed before, the command to add it is still valid on my server from beginning of month

**Comment by BigLOnline** [comment]
it turns out i didnt have the right feed.

**Comment by aikaterna** [comment]
Was going to say, it looks like it's https://www.androidpolice.com/feed/ for that site.

**Comment by BigLOnline** [comment]
apologies. thanks for the swifty responce
