### ISSUE TITLE
[CHATCHART] Failing to load chatchart

### ISSUE THREAD

**Issue by jakjakob** [aikaterna/aikaterna-cogs#330]
Tried solutions:
- ~~update cog~~ (there was no one)
- manually install dependencies via `[p]pipinstall`
- uninstall and reinstall cog

running 3.5.9, haven't tried on 3.5.10 yet though (as soon as I update I will test)
<details>
<summary>traceback</summary>
<code>Jul 27 17:06:24 reddcbotv2 python[1687986]: [2024-07-27 17:06:24] [ERROR] red: Package loading failed
Jul 27 17:06:24 reddcbotv2 python[1687986]: Traceback (most recent call last):
Jul 27 17:06:24 reddcbotv2 python[1687986]:   File "/home/xxx/redenv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 189, in _load
Jul 27 17:06:24 reddcbotv2 python[1687986]:     await bot.load_extension(spec)
Jul 27 17:06:24 reddcbotv2 python[1687986]:   File "/home/xxx/redenv/lib/python3.11/site-packages/redbot/core/bot.py", line 1680, in load_extension
Jul 27 17:06:24 reddcbotv2 python[1687986]:     lib = spec.loader.load_module()
Jul 27 17:06:24 reddcbotv2 python[1687986]:           ^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 27 17:06:24 reddcbotv2 python[1687986]:   File "<frozen importlib._bootstrap_external>", line 605, in _check_name_wrapper
Jul 27 17:06:24 reddcbotv2 python[1687986]:   File "<frozen importlib._bootstrap_external>", line 1120, in load_module
Jul 27 17:06:24 reddcbotv2 python[1687986]:   File "<frozen importlib._bootstrap_external>", line 945, in load_module
Jul 27 17:06:24 reddcbotv2 python[1687986]:   File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
Jul 27 17:06:24 reddcbotv2 python[1687986]:   File "<frozen importlib._bootstrap>", line 721, in _load
Jul 27 17:06:24 reddcbotv2 python[1687986]:   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
Jul 27 17:06:24 reddcbotv2 python[1687986]:   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
Jul 27 17:06:24 reddcbotv2 python[1687986]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Jul 27 17:06:24 reddcbotv2 python[1687986]:   File "/home/xxx/.local/share/Red-DiscordBot/data/craftdcbot/cogs/CogManager/cogs/chatchart/__init__.py", line 1, in <module>
Jul 27 17:06:24 reddcbotv2 python[1687986]:     from .chatchart import Chatchart
Jul 27 17:06:24 reddcbotv2 python[1687986]:   File "/home/xxx/.local/share/Red-DiscordBot/data/craftdcbot/cogs/CogManager/cogs/chatchart/chatchart.py", line 15, in <module>
Jul 27 17:06:24 reddcbotv2 python[1687986]:     import matplotlib
Jul 27 17:06:24 reddcbotv2 python[1687986]:   File "/home/xxx/.local/share/Red-DiscordBot/data/craftdcbot/cogs/Downloader/lib/matplotlib/__init__.py", line 159, in <module>
Jul 27 17:06:24 reddcbotv2 python[1687986]:     from . import _api, _version, cbook, _docstring, rcsetup
Jul 27 17:06:24 reddcbotv2 python[1687986]:   File "/home/xxx/.local/share/Red-DiscordBot/data/craftdcbot/cogs/Downloader/lib/matplotlib/rcsetup.py", line 28, in <module>
Jul 27 17:06:24 reddcbotv2 python[1687986]:     from matplotlib.colors import Colormap, is_color_like
Jul 27 17:06:24 reddcbotv2 python[1687986]:   File "/home/xxx/.local/share/Red-DiscordBot/data/craftdcbot/cogs/Downloader/lib/matplotlib/colors.py", line 57, in <module>
Jul 27 17:06:24 reddcbotv2 python[1687986]:     from matplotlib import _api, _cm, cbook, scale
Jul 27 17:06:24 reddcbotv2 python[1687986]:   File "/home/xxx/.local/share/Red-DiscordBot/data/craftdcbot/cogs/Downloader/lib/matplotlib/scale.py", line 22, in <module>
Jul 27 17:06:24 reddcbotv2 python[1687986]:     from matplotlib.ticker import (
Jul 27 17:06:24 reddcbotv2 python[1687986]:   File "/home/xxx/.local/share/Red-DiscordBot/data/craftdcbot/cogs/Downloader/lib/matplotlib/ticker.py", line 144, in <module>
Jul 27 17:06:24 reddcbotv2 python[1687986]:     from matplotlib import transforms as mtransforms
Jul 27 17:06:24 reddcbotv2 python[1687986]:   File "/home/xxx/.local/share/Red-DiscordBot/data/craftdcbot/cogs/Downloader/lib/matplotlib/transforms.py", line 49, in <module>
Jul 27 17:06:24 reddcbotv2 python[1687986]:     from matplotlib._path import (
Jul 27 17:06:24 reddcbotv2 python[1687986]: ImportError: numpy.core.multiarray failed to import</code>
</details>

**Comment by aikaterna** [comment]
Your matplotlib and/or numpy dependencies aren't set up quite right. Try reinstalling. Numpy can be problematic on some systems.

**Comment by jakjakob** [comment]
tried to re-install (again), and didn't work

**Comment by jakjakob** [comment]
(as said above, I already did that before)

**Comment by aikaterna** [comment]
I'm telling you to fix your dependency installs, however you choose to do that, not reinstall the cog.

**Comment by jakjakob** [comment]
Thanks for the help. "Try reinstalling" could mean anything, please in the future explain a bit better what (even if the context is talking about dependencies that does not exactly mean to reinstall dependencies)
