### ISSUE TITLE
command doesnt work?

### ISSUE THREAD

**Issue by MacGyverinf** [aikaterna/aikaterna-cogs#38]
installed the cog, no issues, everything was fine, ran the !cog info aikaterna-cogs away, which it displayed
![image](https://user-images.githubusercontent.com/35081073/52578054-6ff1da00-2df1-11e9-8b08-13df2d7d9824.png)

i cant get it to activate or work...

redbot info:
![image](https://user-images.githubusercontent.com/35081073/52578115-8dbf3f00-2df1-11e9-841a-c2ba1cf0f99e.png)

**Comment by aikaterna** [comment]
Don't know if you've figured this out at this point, but after you add the repo you will need to add the cog as well, once you have installed the cog using the appropriate commands you also need to load the cog. Red v3 doesn't load installed cogs by default. If you need help, see if the cog is listed in your [p]cogs command and load it if needs be.
