### ISSUE TITLE
[Dictionary] Error Reproduced

### ISSUE THREAD

**Issue by Menteroth** [aikaterna/aikaterna-cogs#77]
Not sure if you saw it in support channel long ago. Might as well put it here so it's kept for future reference. 

 So I figured out when this error occurs. It's the first time you define a word after a restart. Defining a second word and there is no error. Restart and define and it gives the error again.

C:\__\coding\Soundwave\cogs\Downloader\lib\PyDictionary\utils.py:5: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 5 of the file C:\__\coding\Soundwave\cogs\Downloader\lib\PyDictionary\utils.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  return BeautifulSoup(requests.get(url).text)

**Comment by aikaterna** [comment]
This was a library issue and not part of the cog's fault, but is now irrelevant with ccad084. Update the cog and give it a try.
