### ISSUE TITLE
[Tools] Add listroles command

### ISSUE THREAD

**Issue by LGACode** [aikaterna/aikaterna-cogs#82]
Please add a command called `listroles` to get a list of roles in a server with role IDs. This cog conflicts with DataUtils from Fixator10-Cogs (cinfo command is already registered), and this cog does more than that one except for this one command.

**Comment by aikaterna** [comment]
I will consider adding listroles but cinfo will not be changed. I have had the tools cog that way since v2.

**Comment by aikaterna** [comment]
Added in https://github.com/aikaterna/aikaterna-cogs/commit/df45fd95483cdd4bdf5a403235dab4a27cc3fd6f as [p]rolelist
