### ISSUE TITLE
[Wolfram] Add a command that shows step-by-step solutions

### ISSUE THREAD

**Issue by jack1142** [aikaterna/aikaterna-cogs#85]
As in title, WolframAlpha API gives access to those (even with free api key) so would be nice if we could get those with a command. API gives option to get solution in image or in text, IMO for mathematical problems it's better to have an image as it renders all symbols properly then and I don't know if there are even step-by-step solutions for non mathematical problems.

I might be interested in helping with this, if it's low-prio for you but no guarantees.

**Comment by aikaterna** [comment]
Hopefully the impl in the last couple wolfram commits works for you and the idea you have there. Let me know if you need anything changed (or submit a PR of your own).
