### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Jeremy2131** [aikaterna/aikaterna-cogs#9]
Hi,i got this error when i write "help" for bot
Yes he send me "away" features but in console i see this
![1](https://user-images.githubusercontent.com/20999549/33797710-7047c466-dd15-11e7-96af-36f9e4c6c511.png)

**Comment by aikaterna** [comment]
Currently away will give you that message if you use the away command in a DM. There doesn't seem to be any issues using it there. Will keep this open to remind me to fix it.

**Comment by aikaterna** [comment]
I tested this on v2 and v3 away today and neither of them seem to have this issue, so closing this. Let me know if you find other issues.
