### ISSUE TITLE
Seen logs erased after every restart of bot/cog

### ISSUE THREAD

**Issue by Skyrid3r** [aikaterna/aikaterna-cogs#92]
So I haven't updated seen in a while, and as of today I received:

```
Traceback (most recent call last):
  File "/home/skyrider/.virtualenvs/redv3/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/skyrider/discord/redv3/cogs/CogManager/cogs/esf-seen/seen.py", line 30, in _seen
    member_seen = await self.config.member(author).member_seen()
  File "/home/skyrider/.virtualenvs/redv3/lib/python3.7/site-packages/redbot/core/config.py", line 259, in __getattr__
    raise AttributeError("'{}' is not a valid registered Group or value.".format(item))
AttributeError: 'member_seen' is not a valid registered Group or value.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/skyrider/.virtualenvs/redv3/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/home/skyrider/.virtualenvs/redv3/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/skyrider/.virtualenvs/redv3/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'member_seen' is not a valid registered Group or value.
```

Which came out of the blue as it worked fine a few days ago. So I decided to update the cog to the latest version. It works fine now again, but yet for some reason everytime I restart the bot and or the cog, I get the message from:

> UltraSSJGoku was seen 1 minute ago

To

> I haven't seen that user yet.

I'm using MongoDB, though want to convert it back to json but unable to do so as of yet due to some issues in the current RED 3.1.8 version to convert mongodb back to json.

When I check MongoDB, I assume the table I should be looking at is Seen.MEMBER, which has over 5000 records, so that seems to be in order. 

The UltraSSJGoku was actually found in the MongoDB:

> /* 121 */
> {
>     "_id" : {
>         "RED_uuid" : "2784481001",
>         "RED_primary_key" : [ 
>             "170074167549362177", 
>             "357591482007289856"
>         ]
>     },
>     "member_seen" : 1577380764
> }
> 

To human time: GMT: Thursday 26 December 2019 17:19:24, which is also accurate as this is a test account. Haven't used it in a while.

Settings.json in /Seen/ has been last written in 15/05/2019, before I moved it all to mongoDB. Doesn't appear to be used anymore either.

It appears that the cog seen data isn't saving to mongodb properly?

**Comment by aikaterna** [comment]
Your line numbers are different than what's in the published cog. `member_seen = await self.config.member(author).member_seen()` in particular has not been in this cog for quite a few commits now (at least since 3.0.2 or so, didn't nail down the commit where this was changed - probably the caching that Draper added). Reinstall the repo and re-add the cog.

On top of this, as was mentioned in the cog server about this issue, Mongo is being removed soon(tm) with Red 3.2. If there are any data issues it most likely is the Mongo driver and how it interprets Config instructions.
