### ISSUE TITLE
Feature Request for Timezone Cog

### ISSUE THREAD

**Issue by KTCAOP** [aikaterna/aikaterna-cogs#93]
Request to allow people to compare timezones for others:

+time compare [user]
compares your timezone against a user's timezone

so that the output would be like:

KT's Time is 10:17 AM (GMT-7) which is the same timezone as you

KT's Time is 10:17 AM (GMT-7) which is the three hours ahead of you

You have not yet set your own timezone

That user has not yet set their timezone

Please let me know if you need me to flesh out any additional ideas.

**Comment by aikaterna** [comment]
Hello KTCAOP, you can find this implemented in ebb8b31.
