### ISSUE TITLE
[Tools] Please add !joined command

### ISSUE THREAD

**Issue by thisisjvgrace** [aikaterna/aikaterna-cogs#96]
Hi,

Is it possible for you to add a !joined command, where bot simply returns the date you joined the guild and also states how many days ago you joined as well. Your tools cog is a great utility cog so this command would be a nice addition.

**Comment by aikaterna** [comment]
I could do this, but is there a reason why the core command of [p]userinfo wouldn't work for you? The information you're looking for is in that command. The command lives in the mod cog so that would need to be loaded for userinfo to work.

**Comment by aikaterna** [comment]
I will be closing this issue soon as I have not heard back from you. Leaving it open for now in case you would still like to participate.

**Comment by thisisjvgrace** [comment]
Yes, the reason [p]userinfo command wouldn't work for me because it also prints other additional info with it which is unnecessary and spammy in chat. Whereas [p]joined command would simply return 1 line which looks quite clean in output and very less spammy in chat. In my server, we allow bot to interact with users in general channel so I hope you get my point. :D

**Comment by aikaterna** [comment]
You can find this in 87a899f.
