### ISSUE TITLE
how can i add member count, server count etc into rndstatus set?

### ISSUE THREAD

**Issue by maxbooiii** [aikaterna/aikaterna-cogs#99]
The title ask the question... but to explain what i've tried: 
 
i've used these: {member_count}, {user_count}, {server_count}, {prefix}. these is what i've used into the set command but it doesn't show numbers into the status, it shows exactly what i type but no numbers of servers, members and users... iknow i can use [p]rndstatus botstats, but i want more things into the status... but seems like it doesn't work like that, if there's a list on how i can do it??

**Comment by aikaterna** [comment]
rndstatus does not support use of objects as you've asked for, and botstats is hardcoded for the structure of the status. If someone wants to add this I would be open to a PR, but in my opinion rndstatus needs to be rewritten without dependency on an on_message firing for status cycling and to clean up some of the structure.

**Comment by maxbooiii** [comment]
Okey, understandable. thank you. :)
